apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-depl
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: {{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          env:
            - name: SLACK_CHANNEL
              value: {{ .Values.config.slack.channel | quote }}
          # command:
          #   - /bin/sleep
          #   - "9999"
          args:
            - --config
            - "config/config.yaml"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap: 
            name: bot-demo
          
